### ISSUE TITLE
[Remoto] Desenvolvedor Python na YACOWS

### ISSUE THREAD

**Issue by megandavulpi** [backend-br/vagas#537]
### Sobre a empresa: YACOWS

Trabalhando com estratégia, consultoria e desenvolvimento de soluções desde 2010, a YACOWS tem ajudado diversos clientes a se posicionar de forma inovadora na internet. A YACOWS criou empresas ramificadas especializadas em marketing direto, como Telecom e Big Data.

### Descrição:

Atividades do nosso programador:

Desenvolvimento de sistemas Back-End em Python em projetos com foco em APIs de serviços de terceiros.

### Você deve conhecer:

Python;
Django;
APIs;
DevOps;
Banco de Dados.
Será considerado um diferencial o profissional que apresentar conhecimento em Engenharia Reversa.

### Aqui você terá:

Férias;
13º Salário.

### Gostamos de pessoas:

Comprometidas;
Auto gerenciáveis;
Não tenham medo de desafios;
Busquem por novas linguagens e projetos;
Sejam focadas em resolver problemas complexos.
Informações complementares:
Experiência mínima de 5 anos na área.

### Labels

Remoto
Senior

### Candidatar: http://bit.ly/yacows_github

**Comment by xspager** [comment]
Olá, eu cliquei no link e tentei logar com a conta do Linkdin, há outra forma de me candidatar a vaga?

**Comment by taciocabral** [comment]
Também não!

**Comment by taciocabral** [comment]
Também não estou conseguindo me cadastrar?

**Comment by megandavulpi** [comment]
> Também não estou conseguindo me cadastrar?

Olá @taciocabral, pode me explicar mais detalhadamente o porque você não conseguiu se cadastrar? Também foi algo relacionado ao Linkedin?

De qualquer forma, me passe o seu e-mail, vamos entrar em contato o mais rápido possível para te colocar no processo da vaga.

**Comment by megandavulpi** [comment]
> Olá, eu cliquei no link e tentei logar com a conta do Linkdin, há outra forma de me candidatar a vaga?

Olá @xspager , o Linkedin é um pre-requisito para se cadastrar em nossa plataforma.

Pode me explicar mais detalhadamente o porque você não conseguiu se cadastrar? 

De qualquer forma, me passe o seu e-mail, vamos entrar em contato o mais rápido possível para te colocar no processo da vaga.

**Comment by xspager** [comment]
@megandavulpi, acabei de tentar novamente e consegui. Antes dava uma mensagem de erro que não capturei após eu dar a permissão de acesso ao meu Linkedin.

**Comment by silasvasconcelos** [comment]
Olá, fui logar na plataforma e me retornou essa mensagem:

Code: unknown, Error: HTTPSConnectionPool(host='api.linkedin.com', port=443): Max retries exceeded with url: /v1/people/~:(id,first-name,last-name,email-address,picture-url,public-profile-url,headline,location,industry,num-connections,num-connections-capped,summary,specialties,positions)?format=json&oauth2_access_token=AQXv-YLazRS7BpVyBetEreuKnQj8g-bfhN8e8DJH9VGNzzclSncEfFyt_0uR9io7X6i092niVoSqn7xQ99y5rpuIDVWvdtpki6Dt3sR4SJu_RigJQhwuP1y38SVmWHife-pI2D32Sd-270sRjCJMojkIEIV28t35ogY10HzWa_Zwc-iTL3YwrHoE3AbIWLUmOK1ocAOp4___ZeuIHVN-up1Nu9O8LXKpmO_qGQ3Z-0T13tTB3dXPfL5C-IJXR0-e7F8bquSBt_d-Tv7z00vKvuHewA7Qq16veHjx1-qQeh-_StBv7Mnj8-vNpzRDCkrKHR72gRvq0mZOUVJ8IQiOhq8Y7iW2UA (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7732d2a978>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by taciocabral** [comment]
@megandavulpi 
Code: unknown, Error: HTTPSConnectionPool(host='api.linkedin.com', port=443): Max retries exceeded with url: /uas/oauth2/accessToken?client_id=78r4qdz8awjv9y&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fapi.vulpi.com.br%2Fv1%2Fauth%2Faccount%2Flinkedin_oauth2%2Flogin%2Fcallback%2F&code=AQSEM2UKlKtOOV8-JZwVlVRUhvDyiukeTEdZ4-hkTRHYdVzf2HdPEgqJCdBAv6zdboo7JXx0H5CI2zZXFtVUf5dtSvlpa8fB9yPjwEHnJbE0U6xpC6GnpWkV6QPeuhtMK4b1RgRhFS_-cADVET-99oC_A5AtXdnthceI_QqtWnTRIY1SWMCVVgI7JRhXWA&client_secret=PpahqWSJXjsZKdV0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7731a497b8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)) 


E-mail: tacio_cabral@yahoo.com.br

**Comment by megandavulpi** [comment]
Já repassei esse erro para o time de produto pessoal, estamos trabalhando para resolver o quanto antes.

Quem quiser se cadastrar na vaga pode me enviar o e-mail por aqui que entraremos em contato, ok?

Desculpem pelo transtorno.

**Comment by taciocabral** [comment]
Obrigado @megandavulpi.
Passei o e-mail na resposta acima.

**Comment by megandavulpi** [comment]
> Obrigado @megandavulpi.
> Passei o e-mail na resposta acima.

Obrigada, Tacio!

**Comment by reginaldojunior** [comment]
Issue fechada pelo bot. Motivo: Sem interações em um periodo de 3 meses.
